### ISSUE TITLE
@AutoSource 에 생성할 파라미터 갯수 제어 방법 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [AutoParams/AutoParams#162]
#101 을 보다 보니 `@ParameterizedTest` 에 의존하고 있는 AutoParams 에서는 간단히 특정 애노테이션 파라미터 생성을 skip 하도록 제어하지는 못 할 거 같습니다. 
이 충돌은 AutoParams 의 문제가 아니라 `@ParameterizedTest` 와 SpringExtension 에서도 동일하게 발생합니다.

@ParameterizedTest 에서는 다음과 같이 Source 에 해당하는 parameter 를 제어할 수 있습니다.
@CsvSource 의 경우 하나의 Source 가 , 로 구분되서 각각의 파라미터에 입력됩니다.

```java
@ParameterizedTest
@CsvSource({"test,TEST", "tEst,TEST", "Java,JAVA"})
void test(String input, String expected) {
}
```

그래서 Source 의 갯수 이후의 파라미터는 @Autowired 등의 파라미터가 위치해도 문제가 없습니다.

```java
@ParameterizedTest
@CsvSource({"test,TEST", "tEst,TEST", "Java,JAVA"})
void test(String input, String expected, @Autoiwred TestRepository repository) {
}
```

@AutoSource 에서도 생성할 객체에 해당하는 파라미터 갯수를 입력받게 하고, 해당 index 이후 파라미터에 다른 Extension 이 처리하도록 하면 어떨까 합니다.

```java
@ParameterizedTest
@AutoSource(parameterCount = 2)
void test(String input, String expected, @Autoiwred TestRepository repository) {
}
```

의견 부탁드립니다.

**Comment by gyuwon** [comment]
저도 비슷한 생각을 하는 중인데 매개변수 수를 기록하는 방식을 사용하면 테스트를 작성하는 과정에서 매개변수 수를 계속 세어봐야하는 문제가 있습니다. 그래서 저는 마지막 매개변수에 애노테이션을 사용하는 방법을 고민중입니다.

**Comment by mhyeon-lee** [comment]
말씀하신 방법이 아래와 같이 생성하려는 마지막 파라미터에 마킹을 해서 알려주는 방식일까요?

```java
@ParameterizedTest
@AutoSource
void test(String input1, String input2, @LastSource String input3, @Autoiwred TestRepository repository) {
}
```

**Comment by gyuwon** [comment]
네 그런식으로 고민해보고 있어요.

**Comment by mhyeon-lee** [comment]
@gyuwon @jwChung 
어떤 방법이 좋을지 의견 부탁드려요  애노테이션 이름도 부탁드립니다.

1. AutoSource 마지막 매개변수에 마킹 애노테이션을 붙인다.
```java
@ParameterizedTest
@AutoSource
void test(String input1, String input2, @LastSource String input3, @Autoiwred TestRepository repository) {
}
```

2. AutoSource 가 아닌 매개변수 시작점에 마킹 애노테이션을 붙인다.
```java
@ParameterizedTest
@AutoSource
void test(String input1, String input2, String input3, @NoAutoSource @Autoiwred TestRepository repository) {
}
```

**Comment by gyuwon** [comment]
@mhyeon-lee 둘 다 저도 떠올려봤던 건데 모두 별로 맘에 안들면서 더 나은 것도 떠오르지 않네요 ㅋㅋ

**Comment by jwChung** [comment]
@mhyeon-lee @gyuwon

다음과 같이 현재의 data source annotation처럼 동작하면 어떨까요?

```java
@ParameterizedTest
@CsvSource("1,2")
void test(int value1, int value2, @Autowired Foo foo) { //  성공
}

@ParameterizedTest
@CsvSource("1,2")
void test(int value1, @Autowired Foo foo, int value2) { //  실패 :  @Autowired  중간에 낌.
}

@ParameterizedTest
@CsvSource("1,2")
void test(int value1, int value2, @Autowired Foo foo, int value3) { //  실패:  @Autowired 이후 value3이 @Autowired이 아님. 
}
```
`@Autowired ` 이전은 autno source 대상 매개변수로 보고, 이후는 모두 `@Autowired `  으로 지정된 것으로 말이죠.

**Comment by mhyeon-lee** [comment]
@jwChung `@Autowired` 를 포함해서 몇가지를 블랙리스트로 관리해야 되는군요

**Comment by gyuwon** [comment]
@jwChung Autowired나 기타 스프링 코드에 의존할 계획은 없습니다.

**Comment by jwChung** [comment]
@gyuwon  @mhyeon-lee 

스프링에 의존하자는 뜻은 아니었습니다만, `parameterCount` `@ LastSource` 이런 접근이 `@Autowired`를 의존하지 않기 위한 방법이었군요.

----------------------------

https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/ParameterizedTest.html

> 1. Zero or more indexed arguments must be declared first.
> 2. Zero or more aggregators must be declared next.
> 3. Zero or more arguments supplied by other ParameterResolver implementations must be declared last.

위 Parameterzied Test 매개변수를 생성하는 룰에 따르면, `ObjectGenerationContext.generate(...)`를 이용해 `AutoParameterResolver` 를 구현하고 `@ExtendWith({SpringExtension.class, AutoParameterResolver})`  가지는 테스트 어노테이션을 만들어 사용할 수 있겠네요. 그러면 `@Autowired`를 먼저 resolve하고 나머지 non-autowired를 `AutoParameterResolver`가 담당할 수 있지 않을까 합니다. 아직 전부 코드로 돌려서 확인한 상태는 아닙니다.

**Comment by mhyeon-lee** [comment]
@jwChung `ParameterResolver` 구현을 염두하고 말씀하신거 같아 보입니다. 맞을까요?
저도 처음에는 `ParameterResolver` 구현으로 각 매개변수 단위로 판단할지를 결정할 수 있을 줄 알았는데, `@ParameterizedTest` 의 `ParameterizedTestExtension` 를 의존하는 방식으로 진행하고 있어서 별도의 Extension 을 구현해서 제어하는 방향성은 아닌거 같습니다.

`ParameterizedTestExtension` 안의 룰에 맞춰 확장해야 하며, `ArgumentsProvider` 는 매개변수 `0 ~ last index` 범위를 지정해서만 생성할 매개변수 대상을 제어할 수 있습니다.

**Comment by jwChung** [comment]
@mhyeon-lee `ParameterResolver`  각각이 전체 parameter 리스트를 훑고 있어서 직관적인 방법을 찾기가 쉽지 않군요. 아래 이슈에서 말한 `CompositeParameterResolver`를 `ParameterizedTestExtension` 내에서도 사용할 수 있으면 좋겠군요.

https://github.com/junit-team/junit5/issues/1604

**Comment by gyuwon** [comment]
@mhyeon-lee 제안해주신 `@NoAutoSource` 이름을 `@Trim`으로 하는 건 어떨까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
`@Trim` 은 왠지 String # trim 이 떠오르긴 하지만 딱히 좋은 이름도 없네요
`@TrimArgs` 는 이상할까요?

**Comment by gyuwon** [comment]
Trim이 절삭이란 뜻이고 String 클래스가 이 의미를 사용한 거라 괜찮지 않을까 하는게 의견입니다. :) 제가 통계학 전공이라 자연스럽게 느낄 수도 있겠네요.

**Comment by gyuwon** [comment]
@mhyeon-lee @jwChung 이 문제 해결하는데 3년이나 걸렸네요. 🥲

https://github.com/AutoParams/AutoParams/blob/7635e33a4e8d7bc441eef120f6843138b20e1687/test-autoparams-springboot/src/test/java/test/autoparams/MessageApplicationTests.java#L19-L46

이제 이 이슈는 닫겠습니다. 다른 의견 있으면 말씀해주세요!
