### ISSUE TITLE
코틀린 지원 라이브러리 추가

### ISSUE THREAD

**Issue by wplong11** [AutoParams/AutoParams#285]
#284 와 같은 코틀린에서 쓸 편의 도구를 제공하는 라이브러리를 추가한다

(참고) https://github.com/mockito/mockito-kotlin

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee 어떻게 생각하시나요?

**Comment by jwChung** [comment]
@wplong11 님,

1. 말씀하시는 편의도구가 문법설탕(syntactic sugar)으로 이해하면 될까요? 
1. 필요에 따라 사용자가 직접 작성할 수 있는데 라이브러리로 제공할 만큼의 코드량이 있을까요?

------------------------

@wplong11 @mhyeon-lee @gyuwon 

2번에서 일정 정도의 코드 작성이 필요하다면, AutoParams repo가 아닌 별도의 repo를 생성해 진행하는게 좋을 것 같습니다.

**Comment by mhyeon-lee** [comment]
@gyuwon @jwChung 
필요한 케이스가 몇개 모이면 추가하면 어떨까 싶습니다.
별도 repo 로 구성할 수도 있지만, 이 repo 에 모듈 추가해도 될거 같고요

**Comment by gyuwon** [comment]
그렇다면 우선 gist로 몇개 작성해보면 어떨까요?

**Comment by gyuwon** [comment]
autoparams-kotlin 모듈이 추가되었기 때문에 이 이슈는 닫겠습니다. :)
