### ISSUE TITLE
@Mock 애노테이션 지원

### ISSUE THREAD

**Issue by gyuwon** [AutoParams/AutoParams#292]

**Comment by wplong11** [comment]
혹시 아래 내용과 관련있나요?
https://github.com/AutoParams/AutoParams/issues/269

**Comment by gyuwon** [comment]
@wplong11 앗, 아니에요. 이건 Mockito를 사용할 때 `mock()` 메서드를 사용할 지 `spy()` 메서드를 사용할지 결정하게 하기 위함이 목적입니다.
