### ISSUE TITLE
public constructor가 존재하지 않는 generated protobuf message를 지원하는 모듈 추가 요청

### ISSUE THREAD

**Issue by Min3953** [AutoParams/AutoParams#296]
protobuf message를 AutoSource를 이용하여 인수로 받기 위해서 지금버전에서는 message별로 Customizer를 일일이 구현해야 합니다.
위와 같은 행위는 매우 반복적이며 피로도가 심한 작업이기 때문에 protobuf message를 지원할 수 있도록 모듈 추가 요청을 합니다.

`T extends MessageOrBuilder`인(MessageOrBuilder는 protobuf java의 root interface입니다) ```Class<T>```를 인수로 받아 T를 생성할 수 있는 방법은 존재하며 구현할 수 있습니다.
모듈이 추가된다면 해당 로직을 이용하여 충분히 구현이 가능할것이라고 판단됩니다.

검토 부탁드립니다.

**Comment by gyuwon** [comment]
@Min3953 ProtoBuf 를 지원하는 패키지 추가를 검토하겠습니다!

**Comment by gyuwon** [comment]
@Min3953 `MessageOrBuilder` 형식을 살펴볼 수 있는 링크 좀 부탁드려도 될까요?

**Comment by Min3953** [comment]
@gyuwon
https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/MessageOrBuilder.java
위 interface링크를 말씀하시는건지는 잘 모르겠지만 링크 첨부합니다!
더 필요한 내용이 있으면 말해주세요!

**Comment by Min3953** [comment]
추가로 protobuf를 java로 generation하면 message들이 
[GeneratedMessageV3](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java)를 상속받아서 구현된 결과가 나오게 됩니다

**Comment by gyuwon** [comment]
@Min3953 음 알려주신 링크 봤는데 사용법을 잘 모르겠네요. 사용법을 이해하려면 어떤 문서를 읽어보면 좋을까요?

**Comment by Min3953** [comment]
@gyuwon https://protobuf.dev/reference/java/api-docs/com/google/protobuf/DynamicMessage
제가 임의의 message를 생성할때 사용한 message 입니다.
특정 protobuf class를 이용하여 해당 class의 Descriptor를 읽어 온 후 DynamicMessage로 생성 후 type converting을 이용하여 임의의 protobuf message instance를 생성했습니다.
protobuf 모듈 생성에 동의하신다면 제가 만들어놓은 Util 논리들을 PR로 첨부하겠습니다!

**Comment by gyuwon** [comment]
@Min3953 이 이슈는 닫겠습니다. 추가 의견 있으시면 다시 열어주세요.
