### ISSUE TITLE
문서를 위한 웹 추가

### ISSUE THREAD

**Issue by jinhoyim** [AutoParams/AutoParams#308]
문서가 있으면 좋을 것 같아서 샘플을 만들어봤습니다.
[https://autoparamssample.github.io/](https://autoparamssample.github.io/)

깃헙 리드미에 있는 내용을 토대로 작업 중입니다.
웹 문서를 작성하면 당분간 중복을 유지하거나 깃헙 리드미와 Release 쪽은 새로 추가된 기능 위주로 문서를 남기고 자세한 내용을 웹에 남기면 좋을 것 같습니다.

웹 문서를 유지할 때 기대되는 점은 다음과 같습니다.
- SEO 를 통한 노출
- 코틀린 예제 코드 접근성 개선
- 버전별 문서
- 사이트 내 검색
- 다국어 지원

웹을 오픈소스 리포지토리에 포함하는 경우 함께 커밋될 수 있는 장점이 있고, 라이브러리 코드와 관계 없는 번역과 같은 커밋이 히스토리에 섞이는 것은 단점일 것 같습니다. 포함하는 곳도 많고 별도 리포를 두는 곳도 많네요.
웹 문서 작성에 동의해주실 때 현재 리포에 문서를 포함하고자 하신다면 **경로 이름**을, 외부 리포에 둔다면 autoparams.github.io **리포지토리 생성**을 요청드립니다.

autoparams.github.io 이름의 리포를 사용할 경우 그대로 깃헙 페이지 경로로 사용할 수 있고 그렇지 않은 경우 autoparams.github.io/<리포이름> 을 경로로 사용해야 합니다.

**Comment by gyuwon** [comment]
@jinhoyim 제가 깃헙 알림을 잘 안봐서 확인이 늦었습니다. 🙏 우선 너무 감사드리고요! 👍 기여자 분들과 논의해보고 피드백 드리겠습니다.
