### ISSUE TITLE
infinite value generator 지원

### ISSUE THREAD

**Issue by jwChung** [AutoParams/AutoParams#76]
infinite value generator 를 지원하여 사용자가 특정 조건의 값을 골라  사용할 수 있도록 한다.

```java
@ParameterizedTest
@AutoSource
void sut_supports_infinite_value_generator(InfiniteStream<Integer> stream) {
    Stream<Integer> values = stream.filter(x -> x > 0).distinct().limit(10);
    ...
}
```

**Comment by mhyeon-lee** [comment]
저는 Stream, IntStream, LongStream, DoubleStream 을 Infinite 로 제공하고 limit 으로 알아서 필요한 만큼 가져가는걸 생각하긴 했습니다.

**Comment by jwChung** [comment]
@mhyeon-lee 이미 구현된 stream은 개수가 3개로 고정된 걸로 알고 있습니다. 그래서 infinite 기능 추가를 위해 이 이슈를 만들었습니다.

**Comment by jwChung** [comment]
stream 이 무한으로 표현하면 맴버 필드로 사용되면서, 무한 루프에 빠질 것 같습니다. strea은 개수를 고정 시켜야 하지 않을까 합니다.

**Comment by mhyeon-lee** [comment]
@jwChung 그렇겠네요 의견주신대로 별도의 타입으로 제시하는게 좋겠네요

**Comment by gyuwon** [comment]
AutoFixture의 `Generator<T>` 군요. `InfiniteStream<>` 이란 형식은 지정해야 하는거죠?

**Comment by jwChung** [comment]
@gyuwon 네, `InfiniteStream<T>` 는 public 으로 노출되어 테스트 메소드 매개변수 타입으로 사용되어야 합니다. 생성자는 non-public 으로 구현할 필요가 있습니다.

**Comment by gyuwon** [comment]
이건 customization API 논의 후 처리하는 것이 어떨까요?

**Comment by jwChung** [comment]
@gyuwon 네 좋습니다.

**Comment by jwChung** [comment]
#3 논의 후 처리

**Comment by jwChung** [comment]
이 이슈 `InfiniteGenerator<T>` 타입을 public API로 드러내고, 진행하는 것에 대해 어떻게 생각하세요?

**Comment by gyuwon** [comment]
@jwChung 저는 `Builder<>` 설계를 보고 `Builder<T>`가 `Stream<T>`를 구현해 말씀하신 기능을 지원하는 건 어떨까 하는 생각도 있습니다.

**Comment by jwChung** [comment]
@gyuwon builder.build() 메소드 대신 builder.stream() 메소드를 생각해볼 수 있겠네요. builder와 같이 생각해도 좋을 것 같네요.
```java
builder.stream().filter(...).limit(123);
```

**Comment by gyuwon** [comment]
@jwChung 그것도 괜찮네요. 좀 더 명시적이고.

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee `Factory<T>` 클래스 도입으로 이 이슈는 해결된 것으로 하겠습니다. 다른 의견 있으시면 다시 열어주세요!
https://github.com/AutoParams/AutoParams/blob/8529d589fa36c169051a5a19b8663a713dc858e4/autoparams/src/main/java/autoparams/generator/Factory.java
