### ISSUE TITLE
슬슬 아이콘 같은 거 필요하지 않나요? 🤣

### ISSUE THREAD

**Issue by gyuwon** [AutoParams/AutoParams#82]

**Comment by jwChung** [comment]
프로와 아마 차이를 결정 짓는 중요한 요소라 생각합니다. ㅋㅋ

**Comment by gyuwon** [comment]
![image](https://user-images.githubusercontent.com/973743/111858351-9349c480-897b-11eb-9a6e-86e34da04efc.png)
